baseurl = "https://zxjack.netlify.com/"
title = "游侠客 BLOG"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = "zxjack"
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/shanghai.JPG"
  SEOTitle = "游侠客的博客 | Zhengx Blog"
  description = "游侠客，生活探险家 | 这里是 游侠客 的博客，与你一起发现更大的世界。"
  keyword = "游侠客, Zhengx, Zhengx, , 游侠客的网络日志, 游侠客的博客, Zhengx Blog, 博客, 个人网站, 互联网,"
  slogan = "路在脚下，心向远方"

  image_404 = "img/404-bg.jpg"
  title_404 = "你来到了没有知识的荒原 :("

  # leancloud storage for page view counter
  page_view_conter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = true 
  algolia_appId = "9PSMF1UKKB"
  algolia_indexName = "dev_zxjackhugo"
  algolia_apiKey = "bcd0905a724756cf364c79be83fb7508"

  # Sidebar settings
  sidebar_about_description = "在哪里都是自己的天堂"
  sidebar_avatar = "img/my.png"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 2 

  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  disqus_proxy = ""
  disqus_site = ""

  [params.social]
  rss            = true 
  email          = "zxjack@gmail.com"
  facebook      = "https://www.facebook.com/zxjack"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  #linkedin       = "full profile url in linkedin"
  #stackoverflow  = "full profile url in stackoverflow"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/zxjack"
  #wechat         = "link of wechat QR code image"
  #pinterest     = "full profile url in pinterest"
  
  #[[params.friend_link]]
  #title = "Linda的博客"
  #href =  "https://zhaozhihan.com"

  #[[params.bookmark_link]]
  #title =  "Martin Fowler"
  #href =  "https://martinfowler.com"
  #[[params.bookmark_link]]
  #title = "ServiceMesh中文网"
  #href =  "http://www.servicemesh.cn"
  #[[params.bookmark_link]]
  #title = "Awesome Service Mesh"
  #href = "https://servicemesh.gitbooks.io/awesome-servicemesh"
  #[[params.bookmark_link]]
  #title =  "Image Compression"
  #href = "https://tinypng.com"
  
[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 
